// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NFDefine.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NFMsg {

  /// <summary>Holder for reflection information generated from NFDefine.proto</summary>
  public static partial class NFDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for NFDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NFDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ORkRlZmluZS5wcm90bxIFTkZNc2cqlQoKDkVHYW1lRXZlbnRDb2RlEhAK",
            "DEVHRUNfU1VDQ0VTUxAAEhUKEUVHRUNfVU5LT1dOX0VSUk9SEAESFgoSRUdF",
            "Q19BQ0NPVU5UX0VYSVNUEAISGwoXRUdFQ19BQ0NPVU5UUFdEX0lOVkFMSUQQ",
            "AxIWChJFR0VDX0FDQ09VTlRfVVNJTkcQBBIXChNFR0VDX0FDQ09VTlRfTE9D",
            "S0VEEAUSGAoURUdFQ19BQ0NPVU5UX1NVQ0NFU1MQBhIbChdFR0VDX1ZFUklG",
            "WV9LRVlfU1VDQ0VTUxAHEhgKFEVHRUNfVkVSSUZZX0tFWV9GQUlMEAgSHQoZ",
            "RUdFQ19TRUxFQ1RTRVJWRVJfU1VDQ0VTUxAJEhoKFkVHRUNfU0VMRUNUU0VS",
            "VkVSX0ZBSUwQChIYChRFR0VDX0NIQVJBQ1RFUl9FWElTVBBuEhoKFkVHRUNf",
            "U1ZSWk9ORUlEX0lOVkFMSUQQbxIZChVFR0VDX0NIQVJBQ1RFUl9OVU1PVVQQ",
            "cBIaChZFR0VDX0NIQVJBQ1RFUl9JTlZBTElEEHESGwoXRUdFQ19DSEFSQUNU",
            "RVJfTk9URVhJU1QQchIYChRFR0VDX0NIQVJBQ1RFUl9VU0lORxBzEhkKFUVH",
            "RUNfQ0hBUkFDVEVSX0xPQ0tFRBB0EhYKEkVHRUNfWk9ORV9PVkVSTE9BRBB1",
            "EhMKD0VHRUNfTk9UX09OTElORRB2EhcKE0VHRUNfQUxSRUFZX0lOX1RFQU0Q",
            "dxIcChhFR0VDX0lOVkFMSURfVEVBTV9JTlZJVEUQeBISCg5FR0VDX1RFQU1f",
            "RlVMTBB5EhoKFkVHRUNfTUFJTF9VUERBVEVfRVJST1IQehIcChhFR0VDX01B",
            "SUxfVE9OQU1FX0lOVkFMSUQQexIaChZFR0VDX01BSUxfREVMRVRFX0VSUk9S",
            "EHwSGwoXRUdFQ19NQUlMX1RPV05BTUVfRVFVQUwQfRITCg9FR0VDX0xBQ0tf",
            "TU9ORVkQfhIVChFFR0VDX0ZVTExfUEFDS0FHRRB/EhYKEUVHRUNfSU5WQUxJ",
            "RF9JVEVNEIABEh0KGEVHRUNfSU5WQUxJRF9DT05TSUdOTUVOVBCBARIYChNF",
            "R0VDX05PVF9FTk9VR0hfVklQEIIBEhQKD0VHRUNfTkVFRF9MRVZFTBCDARIZ",
            "ChRFR0VDX01BWF9GUklFTkRfTElTVBCEARIYChNFR0VDX01BWF9FTkVNWV9M",
            "SVNUEIUBEhgKE0VHRUNfTUFYX0dBTkdTX0xTSVQQhgESGgoVRUdFQ19MSU1J",
            "VFNfVE9fUklHSFRTEIcBEhwKF0VHRUNfSU5WQUxJRF9HQU5HU19OQU1FEIgB",
            "EhwKF0VHRUNfUkVQRUFUX0VOVEVSX0dBTkdTEIkBEh0KGEVHRUNfSU5WQUxJ",
            "RF9HQU5HU01FTUJFUhCKARIcChdFR0VDX01BU1RFUl9MRUFWRV9HQU5HUxCL",
            "ARIbChZFR0VDX0dBTkdTX1RJVExFX09VVE9GEIwBEh0KGEVHRUNfRU5URVJf",
            "R0FURVdBWV9GQUlMRBCNARIYChNFR0VDX05PX1NFUlZFUjRaT05FEI4BEhcK",
            "EkVHRUNfSU5WQUxJRF9TS0lMTBCPARIdChhFR0VDX0NSRUFURV9DTEFOX1NV",
            "Q0NFU1MQyAESGwoWRUdFQ19KT0lOX0NMQU5fU1VDQ0VTUxDJARIcChdFR0VD",
            "X0xFQVZFX0NMQU5fU1VDQ0VTUxDKASocCglFU3luTXNnSUQSDwoLRVNNSV9V",
            "TktOT1cQACrTMAoKRUdhbWVNc2dJRBIPCgtFR01JX1VOS05PVxAAEhUKEUVH",
            "TUlfRVZFTlRfUkVTVUxUEAESGAoURUdNSV9FVkVOVF9UUkFOU1BPTkQQAhIV",
            "ChFFR01JX0NMT1NFX1NPQ0tFVBADEh0KGUVHTUlfV1RNX1dPUkxEX1JFR0lT",
            "VEVSRUQQChIfChtFR01JX1dUTV9XT1JMRF9VTlJFR0lTVEVSRUQQCxIaChZF",
            "R01JX1dUTV9XT1JMRF9SRUZSRVNIEAwSHQoZRUdNSV9MVE1fTE9HSU5fUkVH",
            "SVNURVJFRBAUEh8KG0VHTUlfTFRNX0xPR0lOX1VOUkVHSVNURVJFRBAVEhoK",
            "FkVHTUlfTFRNX0xPR0lOX1JFRlJFU0gQFhIeChpFR01JX1BUV0dfUFJPWFlf",
            "UkVHSVNURVJFRBAeEiAKHEVHTUlfUFRXR19QUk9YWV9VTlJFR0lTVEVSRUQQ",
            "HxIbChdFR01JX1BUV0dfUFJPWFlfUkVGUkVTSBAgEhwKGEVHTUlfR1RXX0dB",
            "TUVfUkVHSVNURVJFRBAoEh4KGkVHTUlfR1RXX0dBTUVfVU5SRUdJU1RFUkVE",
            "ECkSGQoVRUdNSV9HVFdfR0FNRV9SRUZSRVNIECoSGgoWRUdNSV9EVFdfREJf",
            "UkVHSVNURVJFRBA8EhwKGEVHTUlfRFRXX0RCX1VOUkVHSVNURVJFRBA9EhcK",
            "E0VHTUlfRFRXX0RCX1JFRlJFU0gQPhIVChFFR01JX1NUU19ORVRfSU5GTxBG",
            "EhoKFkVHTUlfU1RTX1NFUlZFUl9SRVBPUlQQWhIXChNFR01JX1NUU19IRUFS",
            "VF9CRUFUEGQSEgoORUdNSV9SRVFfTE9HSU4QZRISCg5FR01JX0FDS19MT0dJ",
            "ThBmEhMKD0VHTUlfUkVRX0xPR09VVBBnEhcKE0VHTUlfUkVRX1dPUkxEX0xJ",
            "U1QQbhIXChNFR01JX0FDS19XT1JMRF9MSVNUEG8SGgoWRUdNSV9SRVFfQ09O",
            "TkVDVF9XT1JMRBBwEhoKFkVHTUlfQUNLX0NPTk5FQ1RfV09STEQQcRIgChxF",
            "R01JX1JFUV9LSUNLX0NMSUVOVF9JTldPUkxEEHISGAoURUdNSV9SRVFfQ09O",
            "TkVDVF9LRVkQeBIYChRFR01JX0FDS19DT05ORUNUX0tFWRB6EhsKFkVHTUlf",
            "UkVRX1NFTEVDVF9TRVJWRVIQggESGwoWRUdNSV9BQ0tfU0VMRUNUX1NFUlZF",
            "UhCDARIXChJFR01JX1JFUV9ST0xFX0xJU1QQhAESFwoSRUdNSV9BQ0tfUk9M",
            "RV9MSVNUEIUBEhkKFEVHTUlfUkVRX0NSRUFURV9ST0xFEIYBEhkKFEVHTUlf",
            "UkVRX0RFTEVURV9ST0xFEIcBEhoKFUVHTUlfUkVRX1JFQ09WRVJfUk9MRRCI",
            "ARIcChdFR01JX1JFUV9MT0FEX1JPTEVfREFUQRCMARIcChdFR01JX0FDS19M",
            "T0FEX1JPTEVfREFUQRCNARIcChdFR01JX1JFUV9TQVZFX1JPTEVfREFUQRCO",
            "ARIcChdFR01JX0FDS19TQVZFX1JPTEVfREFUQRCPARIYChNFR01JX1JFUV9F",
            "TlRFUl9HQU1FEJYBEhgKE0VHTUlfQUNLX0VOVEVSX0dBTUUQlwESGAoTRUdN",
            "SV9SRVFfTEVBVkVfR0FNRRCYARIYChNFR01JX0FDS19MRUFWRV9HQU1FEJkB",
            "EhcKEkVHTUlfUkVRX1NXQVBfR0FNRRCaARIYChNFR01JX1JFUV9TV0FQX1ND",
            "RU5FEJsBEhgKE0VHTUlfQUNLX1NXQVBfU0NFTkUQnAESHQoYRUdNSV9SRVFf",
            "U1dBUF9IT01FX1NDRU5FEJ0BEh0KGEVHTUlfQUNLX1NXQVBfSE9NRV9TQ0VO",
            "RRCeARIfChpFR01JX1JFUV9FTlRFUl9HQU1FX0ZJTklTSBCfARIfChpFR01J",
            "X0FDS19FTlRFUl9HQU1FX0ZJTklTSBCgARIYChNFR01JX1JFUV9BQ0tfUkVM",
            "SVZFELQBEhoKFUVHTUlfQUNLX09CSkVDVF9FTlRSWRDIARIaChVFR01JX0FD",
            "S19PQkpFQ1RfTEVBVkUQyQESIwoeRUdNSV9BQ0tfT0JKRUNUX1BST1BFUlRZ",
            "X0VOVFJZEMoBEiEKHEVHTUlfQUNLX09CSkVDVF9SRUNPUkRfRU5UUlkQywES",
            "GgoVRUdNSV9BQ0tfUFJPUEVSVFlfSU5UENIBEhwKF0VHTUlfQUNLX1BST1BF",
            "UlRZX0ZMT0FUENMBEh0KGEVHTUlfQUNLX1BST1BFUlRZX1NUUklORxDUARId",
            "ChhFR01JX0FDS19QUk9QRVJUWV9PQkpFQ1QQ1gESHgoZRUdNSV9BQ0tfUFJP",
            "UEVSVFlfVkVDVE9SMhDXARIeChlFR01JX0FDS19QUk9QRVJUWV9WRUNUT1Iz",
            "ENgBEhUKEEVHTUlfQUNLX0FERF9ST1cQ3AESGAoTRUdNSV9BQ0tfUkVNT1ZF",
            "X1JPVxDdARIWChFFR01JX0FDS19TV0FQX1JPVxDeARIYChNFR01JX0FDS19S",
            "RUNPUkRfSU5UEN8BEhoKFUVHTUlfQUNLX1JFQ09SRF9GTE9BVBDgARIbChZF",
            "R01JX0FDS19SRUNPUkRfU1RSSU5HEOIBEhsKFkVHTUlfQUNLX1JFQ09SRF9P",
            "QkpFQ1QQ4wESHAoXRUdNSV9BQ0tfUkVDT1JEX1ZFQ1RPUjIQ5AESHAoXRUdN",
            "SV9BQ0tfUkVDT1JEX1ZFQ1RPUjMQ5QESGgoVRUdNSV9BQ0tfUkVDT1JEX0NM",
            "RUFSEPoBEhkKFEVHTUlfQUNLX1JFQ09SRF9TT1JUEPsBEhsKFkVHTUlfQUNL",
            "X0RBVEFfRklOSVNIRUQQhAISFgoRRUdNSV9SRVFfQUlfT05XRVIQrAISGwoW",
            "RUdNSV9SRVFfU1RBUlRfT1BQTkVOVBDECRIbChZFR01JX0FDS19TVEFSVF9P",
            "UFBORU5UEMUJEhkKFEVHTUlfUkVRX0VORF9PUFBORU5UEMYJEhkKFEVHTUlf",
            "QUNLX0VORF9PUFBORU5UEMcJEhwKF0VHTUlfUkVRX1NFQVJDSF9PUFBORU5U",
            "EMgJEhwKF0VHTUlfQUNLX1NFQVJDSF9PUFBORU5UEMkJEhsKFkVHTUlfUkVR",
            "X0FESlVTVF9HQU1CTEUQygkSEgoNRUdNSV9SRVFfTU9WRRDOCRISCg1FR01J",
            "X0FDS19NT1ZFEM8JEhkKFEVHTUlfUkVRX01PVkVfSU1NVU5FENAJEhkKFEVH",
            "TUlfQUNLX01PVkVfSU1NVU5FENEJEhgKE0VHTUlfUkVRX1NUQVRFX1NZTkMQ",
            "0gkSGAoTRUdNSV9BQ0tfU1RBVEVfU1lOQxDTCRIWChFFR01JX1JFUV9QT1Nf",
            "U1lOQxDUCRIWChFFR01JX0FDS19QT1NfU1lOQxDVCRIbChZFR01JX1JFUV9T",
            "S0lMTF9PQkpFQ1RYENgJEhsKFkVHTUlfQUNLX1NLSUxMX09CSkVDVFgQ2QkS",
            "FwoSRUdNSV9SRVFfU0tJTExfUE9TENoJEhcKEkVHTUlfQUNLX1NLSUxMX1BP",
            "UxDbCRIZChRFR01JX1JFUV9JVEVNX09CSkVDVBDcCRIZChRFR01JX0FDS19J",
            "VEVNX09CSkVDVBDdCRIWChFFR01JX1JFUV9JVEVNX1BPUxDeCRIWChFFR01J",
            "X0FDS19JVEVNX1BPUxDfCRISCg1FR01JX1JFUV9DSEFUEOIJEhIKDUVHTUlf",
            "QUNLX0NIQVQQ4wkSFwoSRUdNSV9SRVFfU0FMRV9JVEVNEOQJEhgKE0VHTUlf",
            "UkVRX1NQTElUX0lURU0Q5QkSGgoVRUdNSV9SRVFfUFJPRFVDRV9JVEVNEOYJ",
            "EhcKEkVHTUlfUkVRX1BJQ0tfSVRFTRDnCRIZChRFR01JX1JFUV9BQ0NFUFRf",
            "VEFTSxDoCRIcChdFR01JX1JFUV9DT01QRUxFVEVfVEFTSxDpCRIbChZFR01J",
            "X0FDS19PTkxJTkVfTk9USUZZEIoKEhwKF0VHTUlfQUNLX09GRkxJTkVfTk9U",
            "SUZZEIsKEhkKFEVHTUlfUkVRX0NSRUFURV9DTEFOEJQKEhkKFEVHTUlfQUNL",
            "X0NSRUFURV9DTEFOEJUKEhcKEkVHTUlfUkVRX0pPSU5fQ0xBThCWChIXChJF",
            "R01JX0FDS19KT0lOX0NMQU4QlwoSGAoTRUdNSV9SRVFfTEVBVkVfQ0xBThCY",
            "ChIYChNFR01JX0FDS19MRUFWRV9DTEFOEJkKEhYKEUVHTUlfUkVRX09QUl9D",
            "TEFOEJoKEhYKEUVHTUlfQUNLX09QUl9DTEFOEJsKEhkKFEVHTUlfUkVRX1NF",
            "QVJDSF9DTEFOEJwKEhkKFEVHTUlfQUNLX1NFQVJDSF9DTEFOEJ0KEhoKFUVH",
            "TUlfUkVRX09QUl9DTEFOSU5GTxCeChIaChVFR01JX0FDS19PUFJfQ0xBTklO",
            "Rk8QnwoSHAoXRUdNSV9SRVFfQ0xBTkVDVFlQRUlORk8QoAoSHAoXRUdNSV9B",
            "Q0tfQ0xBTkVDVFlQRUlORk8QoQoSHAoXRUdNSV9TRVRfQ0xBTkVDVFlQRUlO",
            "Rk8QogoSHQoYRUdNSV9SZXFFbnRlckd1aWxkRWN0eXBlEKMKEh4KGUVHRUNf",
            "UkVRX0NSRUFURV9DSEFUR1JPVVAQ+AoSHgoZRUdFQ19BQ0tfQ1JFQVRFX0NI",
            "QVRHUk9VUBD5ChIcChdFR0VDX1JFUV9KT0lOX0NIQVRHUk9VUBD6ChIcChdF",
            "R0VDX0FDS19KT0lOX0NIQVRHUk9VUBD7ChIdChhFR0VDX1JFUV9MRUFWRV9D",
            "SEFUR1JPVVAQ/AoSHQoYRUdFQ19BQ0tfTEVBVkVfQ0hBVEdST1VQEP0KEiQK",
            "H0VHRUNfUkVRX1NVQlNDUklQVElPTl9DSEFUR1JPVVAQ/goSKgolRUdFQ19S",
            "RVFfQ0FOQ0VMU1VCU0NSSVBUSU9OX0NIQVRHUk9VUBD/ChIeChlFR0VDX1JF",
            "UV9JTlZJVEVfQ0hBVEdST1VQEIALEh4KGUVHRUNfQUNLX0lOVklURV9DSEFU",
            "R1JPVVAQgQsSHAoXRUdFQ19SRVFfS0lDS19DSEFUR1JPVVAQggsSHAoXRUdF",
            "Q19BQ0tfS0lDS19DSEFUR1JPVVAQgwsSHwoaRUdFQ19SRVFfQ0hBVEdST1VQ",
            "X1RPX1RFQU0QqgsSHwoaRUdFQ19BQ0tfQ0hBVEdST1VQX1RPX1RFQU0QqwsS",
            "JQogRUdFQ19SRVFfSU5URU5TSUZZTEVWRUxfVE9fRVFVSVAQ3AsSJQogRUdF",
            "Q19BQ0tfSU5URU5TSUZZTEVWRUxfVE9fRVFVSVAQ3QsSGwoWRUdFQ19SRVFf",
            "SE9MRV9UT19FUVVJUBDeCxIbChZFR0VDX0FDS19IT0xFX1RPX0VRVUlQEN8L",
            "EiEKHEVHRUNfUkVRX0lOTEFZU1RPTkVfVE9fRVFVSVAQ4AsSIQocRUdFQ19B",
            "Q0tfSU5MQVlTVE9ORV9UT19FUVVJUBDhCxIjCh5FR0VDX1JFUV9FTEVNRU5U",
            "TEVWRUxfVE9fRVFVSVAQ4gsSIwoeRUdFQ19BQ0tfRUxFTUVOVExFVkVMX1RP",
            "X0VRVUlQEOMLEhQKD0VHRUNfV0VBUl9FUVVJUBDkCxIXChJFR0VDX1RBS0VP",
            "RkZfRVFVSVAQ5QsSHAoXRUdFQ19SRVFfU0VUX0ZJR0hUX0hFUk8Q8AsSHwoa",
            "RUdFQ19SRVFfU1dJVENIX0ZJR0hUX0hFUk8Q8QsSGgoVRUdFQ19SRVFfTUlO",
            "SU5HX1RJVExFEMAMEhoKFUVHRUNfQUNLX01JTklOR19USVRMRRDBDBIXChJF",
            "R0VDX1JFUV9TRU5EX01BSUwQpA0SFwoSRUdFQ19SRVFfRFJBV19NQUlMEKUN",
            "EhkKFEVHRUNfUkVRX0RFTEVURV9NQUlMEKYNEiAKG0VHTUlfQUNLX0NMT05F",
            "X09CSkVDVF9FTlRSWRCIDhIgChtFR01JX0FDS19DTE9ORV9PQkpFQ1RfTEVB",
            "VkUQiQ4SKQokRUdNSV9BQ0tfQ0xPTkVfT0JKRUNUX1BST1BFUlRZX0VOVFJZ",
            "EIoOEicKIkVHTUlfQUNLX0NMT05FX09CSkVDVF9SRUNPUkRfRU5UUlkQiw4S",
            "IAobRUdNSV9BQ0tfQ0xPTkVfUFJPUEVSVFlfSU5UEJIOEiIKHUVHTUlfQUNL",
            "X0NMT05FX1BST1BFUlRZX0ZMT0FUEJMOEiMKHkVHTUlfQUNLX0NMT05FX1BS",
            "T1BFUlRZX1NUUklORxCUDhIjCh5FR01JX0FDS19DTE9ORV9QUk9QRVJUWV9P",
            "QkpFQ1QQlg4SGAoTRUdNSV9SRVFTV0lDSFNFUlZFUhCwDhIYChNFR01JX0FD",
            "S1NXSUNIU0VSVkVSELEOEhkKFEVHTUlfUkVRX0NSRUFURV9URUFNEMQOEhkK",
            "FEVHTUlfQUNLX0NSRUFURV9URUFNEMUOEhcKEkVHTUlfUkVRX0pPSU5fVEVB",
            "TRDGDhIXChJFR01JX0FDS19KT0lOX1RFQU0Qxw4SGAoTRUdNSV9SRVFfTEVB",
            "VkVfVEVBTRDIDhIYChNFR01JX0FDS19MRUFWRV9URUFNEMkOEhkKFEVHTUlf",
            "UkVRX0lOVklURV9URUFNEMoOEhwKF0VHTUlfUkVRX09QUk1FTUJFUl9URUFN",
            "EMsOEhwKF0VHTUlfQUNLX09QUk1FTUJFUl9URUFNEMwOEh8KGkVHTUlfUkVR",
            "X1RFQU1fRU5URVJfRUNUWVBFEM0OEh8KGkVHTUlfQUNLX1RFQU1fRU5URVJf",
            "RUNUWVBFEM4OEhsKFkVHTUlfUkVRX01BUF9HUklEX0lORk8Q7A4SGwoWRUdN",
            "SV9BQ0tfTUFQX0dSSURfSU5GTxDtDhIaChVFR01JX1JFUV9CSUdfTUFQX0lO",
            "Rk8Q7g4SGgoVRUdNSV9BQ0tfQklHX01BUF9JTkZPEO8OEhsKFkVHTUlfUkVR",
            "X0hPTERfTUFQX0dSSUQQ9g4SGwoWRUdNSV9BQ0tfSE9MRF9NQVBfR1JJRBD3",
            "DhIgChtFR01JX1JFUV9MRUFWRV9NU0dfTUFQX0dSSUQQ+A4SIAobRUdNSV9B",
            "Q0tfTEVBVkVfTVNHX01BUF9HUklEEPkOEiAKG0VHTUlfUkVRX0dFVF9NQVBf",
            "R1JJRF9BV0FSRBD6DhIgChtFR01JX0FDS19HRVRfTUFQX0dSSURfQVdBUkQQ",
            "+w4SHgoZRUdNSV9SRVFfTUFQX0dSSURfSFVOVElORxD8DhIeChlFR01JX0FD",
            "S19NQVBfR1JJRF9IVU5USU5HEP0OEh8KGkVHTUlfUkVRX01BUF9HUklEX0tJ",
            "TkdfV0FSEP4OEh8KGkVHTUlfQUNLX01BUF9HUklEX0tJTkdfV0FSEP8OEh4K",
            "GUVHTUlfUkVRX0NNRF9QUk9QRVJUWV9JTlQQkE4SHgoZRUdNSV9SRVFfQ01E",
            "X1BST1BFUlRZX1NUUhCRThIhChxFR01JX1JFUV9DTURfUFJPUEVSVFlfT0JK",
            "RUNUEJJOEiAKG0VHTUlfUkVRX0NNRF9QUk9QRVJUWV9GTE9BVBCTThIcChdF",
            "R01JX1JFUV9DTURfUkVDT1JEX0lOVBCUThIcChdFR01JX1JFUV9DTURfUkVD",
            "T1JEX1NUUhCVThIfChpFR01JX1JFUV9DTURfUkVDT1JEX09CSkVDVBCWThIe",
            "ChlFR01JX1JFUV9DTURfUkVDT1JEX0ZMT0FUEJdOEhgKE0VHTUlfUkVRX0NN",
            "RF9OT1JNQUwQmE4SIQocRUdNSV9SRVFfUVVFUllfU0VSVkVSX1NUQVRVUxDY",
            "TxIcChZFR01JX1JFUV9CVVlfRk9STV9TSE9QEKCcARIcChZFR01JX0FDS19C",
            "VVlfRk9STV9TSE9QEKGcARIgChpFR01JX1JFUV9NT1ZFX0JVSUxEX09CSkVD",
            "VBCinAESIAoaRUdNSV9BQ0tfTU9WRV9CVUlMRF9PQkpFQ1QQo5wBEhsKFUVH",
            "TUlfUkVRX1VQX0JVSUxEX0xWTBCFnQESGgoURUdNSV9SRVFfQ1JFQVRFX0lU",
            "RU0Qhp0BEhwKFkVHTUlfUkVRX0JVSUxEX09QRVJBVEUQh50BEh4KGEVHTUlf",
            "UkVRX1NFQVJDSF9UT19TSEFSRRCw6gESHgoYRUdNSV9BQ0tfU0VBUkNIX1RP",
            "X1NIQVJFELHqARIdChdFR01JX1JFUV9TSEFSRV9UT19BVEFSVBCy6gESHQoX",
            "RUdNSV9BQ0tfU0hBUkVfVE9fQVRBUlQQs+oBKpsBCgpFU2tpbGxUeXBlEhQK",
            "EEVTVF9CUklFRl9TSU5HTEUQABITCg9FU1RfQlJJRUZfR1JPVVAQARIVChFF",
            "U1RfQlVMTEVUX1NJTkdMRRACEhYKEkVTVF9CVUxMRVRfUkVCT1VORBADEhoK",
            "FkVTVF9CVUxMRVRfVEFSR0VUX0JPTUIQBBIXChNFU1RfQlVMTEVUX1BPU19C",
            "T01CEAUqUgoJRUl0ZW1UeXBlEg0KCUVJVF9FUVVJUBAAEgsKB0VJVF9HRU0Q",
            "ARIMCghFSVRfSVRFTRACEgwKCEVJVF9DQVJEEAMSDQoJRUlUX1RPS0VOEAQq",
            "kQEKEUVHYW1lRXF1aXBTdWJUeXBlEhQKEEVRVUlQVFlQRV9XRUFQT04QABIU",
            "ChBFUVVJUFRZUEVfSEVMTUVUEAESEwoPRVFVSVBUWVBFX0FSTU9SEAISEwoP",
            "RVFVSVBUWVBFX1dSSVNUEAMSEgoORVFVSVBUWVBFX1BBTlQQBBISCg5FUVVJ",
            "UFRZUEVfQk9PVBAFKrIBCg9FR2FtZUdlbVN1YlR5cGUSFAoQRUdHU1RZUEVf",
            "R0VNX0FUSxAAEhQKEEVHR1NUWVBFX0dFTV9ERUYQARIVChFFR0dTVFlQRV9H",
            "RU1fRklSRRADEhYKEkVHR1NUWVBFX0dFTV9MSUdIVBAEEhUKEUVHR1NUWVBF",
            "X0dFTV9XSU5EEAUSFAoQRUdHU1RZUEVfR0VNX0lDRRAGEhcKE0VHR1NUWVBF",
            "X0dFTV9QT0lTT04QByrNAQoQRUdhbWVJdGVtU3ViVHlwZRITCg9FR0lUX0lU",
            "RU1fV0FURVIQABIVChFFR0lUX0lURU1fRElBTU9ORBABEhYKEkVHSVRfSVRF",
            "TV9DVVJSRU5DWRACEhEKDUVHSVRfSVRFTV9FWFAQAxIQCgxFR0lUX0lURU1f",
            "SFAQBBIQCgxFR0lUX0lURU1fTVAQBRIQCgxFR0lUX0lURU1fU1AQBhISCg5F",
            "R0lUX0lURU1fUEFDSxAHEhgKFEVHSVRfSVRFTV9NRU1PUllfUE9TEAgqYwoQ",
            "RUdhbWVDYXJkU3ViVHlwZRIQCgxFR0NTVF9VTktOT1cQABISCg5FR0NTVF9T",
            "VFJFTkdUSBABEhEKDUVHQ1NUX0FHSUxJVFkQAhIWChJFR0NTVF9JTlRFTExJ",
            "R0VOQ0UQAyqOAQoRRUdhbWVUb2tlblN1YlR5cGUSFgoSRUdUU1RfVE9LRU5f",
            "UkVCT1JOEAASGAoURUdUU1RfVE9LRU5fUE9TSVRJT04QARIWChJFR1RTVF9U",
            "T0tFTl9CT1VOVFkQAhIYChRFR1RTVF9UT0tFTl9BQ1RJVklUWRADEhUKEUVH",
            "VFNUX1RPS0VOX0JVSUxEEAQqZQoURUdhbWVJdGVtRXhwaXJlZFR5cGUSDgoK",
            "RUdJRVRfTk9ORRAAEhMKD0VHSUVUX1VTRV9USU1FUxABEhMKD0VHSUVUX1JF",
            "QUxfVElNRRACEhMKD0VHSUVUX0VORF9JTkRFWBADKlkKEkVEcmF3RHJvcEl0",
            "ZW1TdGF0ZRIVChFFX0RSQVdfU1RBVEVfTk9ORRAAEhUKEUVfRFJBV19TVEFU",
            "RV9HQUlOEAESFQoRRV9EUkFXX1NUQVRFX1JFQ1YQAipwCg9FR3VpbGRQb3dl",
            "clR5cGUSGgoWQ0xBTl9QT1dFUl9UWVBFX05PUk1BTBAAEiIKHkNMQU5fUE9X",
            "RVJfVFlQRV9WSUNFX1BSRVNJREVOVBABEh0KGUNMQU5fUE9XRVJfVFlQRV9Q",
            "UkVTSURFTlQQAipWCgpFVGFza1N0YXRlEhMKD1RBU0tfSU5fUFJPQ0VTUxAA",
            "Eg0KCVRBU0tfRE9ORRABEhMKD1RBU0tfRFJBV19BV0FSRBACEg8KC1RBU0tf",
            "RklOSVNIEAMqqQIKCUVUYXNrVHlwZRIgChxUQVNLX0xFVkVMX1VQREFURV9T",
            "T01FX0xFVkVMEAASFAoQVEFTS19QQVNTX0VDVFlQRRABEhoKFlRBU0tfUEFT",
            "U19FQ1RZUEVfQ09VTlQQAhIkCiBUQVNLX1BBU1NfU09NRV9UWVBFX0VDVFlQ",
            "RV9DT1VOVBADEhsKF1RBU0tfVVBEQVRFX1NLSUxMX0NPVU5UEAQSFgoSVEFT",
            "S19DT05TVU1FX01PTkVZEAUSGAoUVEFTS19DT05TVU1FX0RJQU1PTkQQBhIU",
            "ChBUQVNLX0FSRU5BX0NPVU5UEAcSGwoXVEFTS19LSUxMX01PTlNURVJfQ09V",
            "TlQQCBIgChxUQVNLX0tJTExfU09NRV9NT05TVEVSX0NPVU5UEAkqdAoIRVBW",
            "UFR5cGUSDAoIUFZQX0hPTUUQABISCg5QVlBfSU5ESVZJRFVBTBABEgwKCFBW",
            "UF9ET1RBEAISEAoMUFZQX1NVUlZJVkFMEAMSEAoMUFZQX0NMQU5fV0FSEAQS",
            "FAoQUFZQX0NMQU5fRFVOR0VPThAFKnMKCUVTaG9wVHlwZRIOCgpFU1RfVU5L",
            "Tk9XEAASEAoMRVNUX0JVSUxESU5HEAESDAoIRVNUX0dPTEQQAhIMCghFU1Rf",
            "SVRFTRADEg0KCUVTVF9FUVVJUBAFEgsKB0VTVF9HRU0QBhIMCghFU1RfQ0FS",
            "RBAHKokBCglFUmFua1R5cGUSDgoKRVJUX1VOS05PVxAAEhQKEEVSVF9QTEFZ",
            "RVJfTEVWRUwQARITCg9FUlRfRklHSFRfVkFMVUUQAhIUChBFUlRfUExBWUVS",
            "X01PTkVZEAMSEgoORVJUX0NMQU5fTEVWRUwQBBIXChNFUlRfQ0xBTl9LSU5H",
            "U09VUkNFEAUqRwoIRU5QQ1R5cGUSEwoPRU5QQ1RZUEVfTk9STUFMEAASEQoN",
            "RU5QQ1RZUEVfSEVSTxABEhMKD0VOUENUWVBFX1RVUlJFVBACKkUKCkVNZWxl",
            "ZVR5cGUSDwoLRVRZUEVfTUVMRUUQABIUChBFVFlQRV9NRUxFRV9EQVNIEAES",
            "EAoMRVRZUEVfUkFOR0VSEAIqVQoORUVmZmVjdE9ialR5cGUSFQoRRVRBUkdF",
            "VFRZUEVfRU5FTVkQABIUChBFVEFSR0VUVFlQRV9TRUxGEAESFgoSRVRBUkdF",
            "VFRZUEVfRlJJRU5EEAIqWAoNRVByb3BlcnR5VHlwZRIOCgpFUFRfVU5LTk9X",
            "EAASEAoMRVBUX1NUUkVOR1RIEAESDwoLRVBUX0FHSUxJVFkQAhIUChBFUFRf",
            "SU5URUxMSUdFTkNFEAMqngEKEEVHYW1lRWxlbWVudFR5cGUSFQoRRUVMRU1F",
            "TlRUWVBFX0ZJUkUQABIWChJFRUxFTUVOVFRZUEVfTElHSFQQARIVChFFRUxF",
            "TUVOVFRZUEVfV0lORBACEhQKEEVFTEVNRU5UVFlQRV9JQ0UQAxIXChNFRUxF",
            "TUVOVFRZUEVfUE9JU09OEAQSFQoRRUVMRU1FTlRUWVBFX0RBUksQBWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NFMsg.EGameEventCode), typeof(global::NFMsg.ESynMsgID), typeof(global::NFMsg.EGameMsgID), typeof(global::NFMsg.ESkillType), typeof(global::NFMsg.EItemType), typeof(global::NFMsg.EGameEquipSubType), typeof(global::NFMsg.EGameGemSubType), typeof(global::NFMsg.EGameItemSubType), typeof(global::NFMsg.EGameCardSubType), typeof(global::NFMsg.EGameTokenSubType), typeof(global::NFMsg.EGameItemExpiredType), typeof(global::NFMsg.EDrawDropItemState), typeof(global::NFMsg.EGuildPowerType), typeof(global::NFMsg.ETaskState), typeof(global::NFMsg.ETaskType), typeof(global::NFMsg.EPVPType), typeof(global::NFMsg.EShopType), typeof(global::NFMsg.ERankType), typeof(global::NFMsg.ENPCType), typeof(global::NFMsg.EMeleeType), typeof(global::NFMsg.EEffectObjType), typeof(global::NFMsg.EPropertyType), typeof(global::NFMsg.EGameElementType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///events
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SUCCESS")] EgecSuccess = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_UNKOWN_ERROR")] EgecUnkownError = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_EXIST")] EgecAccountExist = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNTPWD_INVALID")] EgecAccountpwdInvalid = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_USING")] EgecAccountUsing = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_LOCKED")] EgecAccountLocked = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_SUCCESS")] EgecAccountSuccess = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_VERIFY_KEY_SUCCESS")] EgecVerifyKeySuccess = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_VERIFY_KEY_FAIL")] EgecVerifyKeyFail = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SELECTSERVER_SUCCESS")] EgecSelectserverSuccess = 9,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SELECTSERVER_FAIL")] EgecSelectserverFail = 10,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_EXIST")] EgecCharacterExist = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SVRZONEID_INVALID")] EgecSvrzoneidInvalid = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_NUMOUT")] EgecCharacterNumout = 112,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_INVALID")] EgecCharacterInvalid = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_NOTEXIST")] EgecCharacterNotexist = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_USING")] EgecCharacterUsing = 115,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_LOCKED")] EgecCharacterLocked = 116,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ZONE_OVERLOAD")] EgecZoneOverload = 117,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NOT_ONLINE")] EgecNotOnline = 118,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ALREAY_IN_TEAM")] EgecAlreayInTeam = 119,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_TEAM_INVITE")] EgecInvalidTeamInvite = 120,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_TEAM_FULL")] EgecTeamFull = 121,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_UPDATE_ERROR")] EgecMailUpdateError = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_TONAME_INVALID")] EgecMailTonameInvalid = 123,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_DELETE_ERROR")] EgecMailDeleteError = 124,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_TOWNAME_EQUAL")] EgecMailTownameEqual = 125,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_LACK_MONEY")] EgecLackMoney = 126,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_FULL_PACKAGE")] EgecFullPackage = 127,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_ITEM")] EgecInvalidItem = 128,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_CONSIGNMENT")] EgecInvalidConsignment = 129,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NOT_ENOUGH_VIP")] EgecNotEnoughVip = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NEED_LEVEL")] EgecNeedLevel = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_FRIEND_LIST")] EgecMaxFriendList = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_ENEMY_LIST")] EgecMaxEnemyList = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_GANGS_LSIT")] EgecMaxGangsLsit = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_LIMITS_TO_RIGHTS")] EgecLimitsToRights = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_GANGS_NAME")] EgecInvalidGangsName = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REPEAT_ENTER_GANGS")] EgecRepeatEnterGangs = 137,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_GANGSMEMBER")] EgecInvalidGangsmember = 138,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MASTER_LEAVE_GANGS")] EgecMasterLeaveGangs = 139,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_GANGS_TITLE_OUTOF")] EgecGangsTitleOutof = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ENTER_GATEWAY_FAILD")] EgecEnterGatewayFaild = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NO_SERVER4ZONE")] EgecNoServer4Zone = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_SKILL")] EgecInvalidSkill = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CREATE_CLAN_SUCCESS")] EgecCreateClanSuccess = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_JOIN_CLAN_SUCCESS")] EgecJoinClanSuccess = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_LEAVE_CLAN_SUCCESS")] EgecLeaveClanSuccess = 202,
  }

  public enum ESynMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ESMI_UNKNOW")] EsmiUnknow = 0,
  }

  public enum EGameMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_UNKNOW")] EgmiUnknow = 0,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EGMI_EVENT_RESULT")] EgmiEventResult = 1,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EGMI_EVENT_TRANSPOND")] EgmiEventTranspond = 2,
    /// <summary>
    /// want to close some one
    /// </summary>
    [pbr::OriginalName("EGMI_CLOSE_SOCKET")] EgmiCloseSocket = 3,
    [pbr::OriginalName("EGMI_WTM_WORLD_REGISTERED")] EgmiWtmWorldRegistered = 10,
    [pbr::OriginalName("EGMI_WTM_WORLD_UNREGISTERED")] EgmiWtmWorldUnregistered = 11,
    [pbr::OriginalName("EGMI_WTM_WORLD_REFRESH")] EgmiWtmWorldRefresh = 12,
    [pbr::OriginalName("EGMI_LTM_LOGIN_REGISTERED")] EgmiLtmLoginRegistered = 20,
    [pbr::OriginalName("EGMI_LTM_LOGIN_UNREGISTERED")] EgmiLtmLoginUnregistered = 21,
    [pbr::OriginalName("EGMI_LTM_LOGIN_REFRESH")] EgmiLtmLoginRefresh = 22,
    [pbr::OriginalName("EGMI_PTWG_PROXY_REGISTERED")] EgmiPtwgProxyRegistered = 30,
    [pbr::OriginalName("EGMI_PTWG_PROXY_UNREGISTERED")] EgmiPtwgProxyUnregistered = 31,
    [pbr::OriginalName("EGMI_PTWG_PROXY_REFRESH")] EgmiPtwgProxyRefresh = 32,
    [pbr::OriginalName("EGMI_GTW_GAME_REGISTERED")] EgmiGtwGameRegistered = 40,
    [pbr::OriginalName("EGMI_GTW_GAME_UNREGISTERED")] EgmiGtwGameUnregistered = 41,
    [pbr::OriginalName("EGMI_GTW_GAME_REFRESH")] EgmiGtwGameRefresh = 42,
    [pbr::OriginalName("EGMI_DTW_DB_REGISTERED")] EgmiDtwDbRegistered = 60,
    [pbr::OriginalName("EGMI_DTW_DB_UNREGISTERED")] EgmiDtwDbUnregistered = 61,
    [pbr::OriginalName("EGMI_DTW_DB_REFRESH")] EgmiDtwDbRefresh = 62,
    [pbr::OriginalName("EGMI_STS_NET_INFO")] EgmiStsNetInfo = 70,
    [pbr::OriginalName("EGMI_STS_SERVER_REPORT")] EgmiStsServerReport = 90,
    [pbr::OriginalName("EGMI_STS_HEART_BEAT")] EgmiStsHeartBeat = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOGIN")] EgmiReqLogin = 101,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LOGIN")] EgmiAckLogin = 102,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOGOUT")] EgmiReqLogout = 103,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_WORLD_LIST")] EgmiReqWorldList = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_WORLD_LIST")] EgmiAckWorldList = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CONNECT_WORLD")] EgmiReqConnectWorld = 112,
    [pbr::OriginalName("EGMI_ACK_CONNECT_WORLD")] EgmiAckConnectWorld = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_KICK_CLIENT_INWORLD")] EgmiReqKickClientInworld = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CONNECT_KEY")] EgmiReqConnectKey = 120,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CONNECT_KEY")] EgmiAckConnectKey = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SELECT_SERVER")] EgmiReqSelectServer = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SELECT_SERVER")] EgmiAckSelectServer = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ROLE_LIST")] EgmiReqRoleList = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ROLE_LIST")] EgmiAckRoleList = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_ROLE")] EgmiReqCreateRole = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_DELETE_ROLE")] EgmiReqDeleteRole = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_RECOVER_ROLE")] EgmiReqRecoverRole = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOAD_ROLE_DATA")] EgmiReqLoadRoleData = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LOAD_ROLE_DATA")] EgmiAckLoadRoleData = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SAVE_ROLE_DATA")] EgmiReqSaveRoleData = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SAVE_ROLE_DATA")] EgmiAckSaveRoleData = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ENTER_GAME")] EgmiReqEnterGame = 150,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTER_GAME")] EgmiAckEnterGame = 151,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_GAME")] EgmiReqLeaveGame = 152,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_GAME")] EgmiAckLeaveGame = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_GAME")] EgmiReqSwapGame = 154,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_SCENE")] EgmiReqSwapScene = 155,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SWAP_SCENE")] EgmiAckSwapScene = 156,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_HOME_SCENE")] EgmiReqSwapHomeScene = 157,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SWAP_HOME_SCENE")] EgmiAckSwapHomeScene = 158,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ENTER_GAME_FINISH")] EgmiReqEnterGameFinish = 159,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTER_GAME_FINISH")] EgmiAckEnterGameFinish = 160,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ACK_RELIVE")] EgmiReqAckRelive = 180,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_ENTRY")] EgmiAckObjectEntry = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_LEAVE")] EgmiAckObjectLeave = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_PROPERTY_ENTRY")] EgmiAckObjectPropertyEntry = 202,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_RECORD_ENTRY")] EgmiAckObjectRecordEntry = 203,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_INT")] EgmiAckPropertyInt = 210,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_FLOAT")] EgmiAckPropertyFloat = 211,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_STRING")] EgmiAckPropertyString = 212,
    /// <summary>
    ///EGMI_ACK_PROPERTY_DOUBLE					= 213;			//
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_OBJECT")] EgmiAckPropertyObject = 214,
    [pbr::OriginalName("EGMI_ACK_PROPERTY_VECTOR2")] EgmiAckPropertyVector2 = 215,
    [pbr::OriginalName("EGMI_ACK_PROPERTY_VECTOR3")] EgmiAckPropertyVector3 = 216,
    [pbr::OriginalName("EGMI_ACK_ADD_ROW")] EgmiAckAddRow = 220,
    [pbr::OriginalName("EGMI_ACK_REMOVE_ROW")] EgmiAckRemoveRow = 221,
    [pbr::OriginalName("EGMI_ACK_SWAP_ROW")] EgmiAckSwapRow = 222,
    [pbr::OriginalName("EGMI_ACK_RECORD_INT")] EgmiAckRecordInt = 223,
    [pbr::OriginalName("EGMI_ACK_RECORD_FLOAT")] EgmiAckRecordFloat = 224,
    /// <summary>
    ///EGMI_ACK_RECORD_DOUBLE					= 225;
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_RECORD_STRING")] EgmiAckRecordString = 226,
    [pbr::OriginalName("EGMI_ACK_RECORD_OBJECT")] EgmiAckRecordObject = 227,
    [pbr::OriginalName("EGMI_ACK_RECORD_VECTOR2")] EgmiAckRecordVector2 = 228,
    [pbr::OriginalName("EGMI_ACK_RECORD_VECTOR3")] EgmiAckRecordVector3 = 229,
    [pbr::OriginalName("EGMI_ACK_RECORD_CLEAR")] EgmiAckRecordClear = 250,
    [pbr::OriginalName("EGMI_ACK_RECORD_SORT")] EgmiAckRecordSort = 251,
    [pbr::OriginalName("EGMI_ACK_DATA_FINISHED")] EgmiAckDataFinished = 260,
    [pbr::OriginalName("EGMI_REQ_AI_ONWER")] EgmiReqAiOnwer = 300,
    [pbr::OriginalName("EGMI_REQ_START_OPPNENT")] EgmiReqStartOppnent = 1220,
    [pbr::OriginalName("EGMI_ACK_START_OPPNENT")] EgmiAckStartOppnent = 1221,
    [pbr::OriginalName("EGMI_REQ_END_OPPNENT")] EgmiReqEndOppnent = 1222,
    [pbr::OriginalName("EGMI_ACK_END_OPPNENT")] EgmiAckEndOppnent = 1223,
    [pbr::OriginalName("EGMI_REQ_SEARCH_OPPNENT")] EgmiReqSearchOppnent = 1224,
    [pbr::OriginalName("EGMI_ACK_SEARCH_OPPNENT")] EgmiAckSearchOppnent = 1225,
    [pbr::OriginalName("EGMI_REQ_ADJUST_GAMBLE")] EgmiReqAdjustGamble = 1226,
    [pbr::OriginalName("EGMI_REQ_MOVE")] EgmiReqMove = 1230,
    [pbr::OriginalName("EGMI_ACK_MOVE")] EgmiAckMove = 1231,
    [pbr::OriginalName("EGMI_REQ_MOVE_IMMUNE")] EgmiReqMoveImmune = 1232,
    [pbr::OriginalName("EGMI_ACK_MOVE_IMMUNE")] EgmiAckMoveImmune = 1233,
    [pbr::OriginalName("EGMI_REQ_STATE_SYNC")] EgmiReqStateSync = 1234,
    [pbr::OriginalName("EGMI_ACK_STATE_SYNC")] EgmiAckStateSync = 1235,
    [pbr::OriginalName("EGMI_REQ_POS_SYNC")] EgmiReqPosSync = 1236,
    [pbr::OriginalName("EGMI_ACK_POS_SYNC")] EgmiAckPosSync = 1237,
    [pbr::OriginalName("EGMI_REQ_SKILL_OBJECTX")] EgmiReqSkillObjectx = 1240,
    [pbr::OriginalName("EGMI_ACK_SKILL_OBJECTX")] EgmiAckSkillObjectx = 1241,
    [pbr::OriginalName("EGMI_REQ_SKILL_POS")] EgmiReqSkillPos = 1242,
    [pbr::OriginalName("EGMI_ACK_SKILL_POS")] EgmiAckSkillPos = 1243,
    [pbr::OriginalName("EGMI_REQ_ITEM_OBJECT")] EgmiReqItemObject = 1244,
    [pbr::OriginalName("EGMI_ACK_ITEM_OBJECT")] EgmiAckItemObject = 1245,
    [pbr::OriginalName("EGMI_REQ_ITEM_POS")] EgmiReqItemPos = 1246,
    [pbr::OriginalName("EGMI_ACK_ITEM_POS")] EgmiAckItemPos = 1247,
    [pbr::OriginalName("EGMI_REQ_CHAT")] EgmiReqChat = 1250,
    [pbr::OriginalName("EGMI_ACK_CHAT")] EgmiAckChat = 1251,
    [pbr::OriginalName("EGMI_REQ_SALE_ITEM")] EgmiReqSaleItem = 1252,
    [pbr::OriginalName("EGMI_REQ_SPLIT_ITEM")] EgmiReqSplitItem = 1253,
    [pbr::OriginalName("EGMI_REQ_PRODUCE_ITEM")] EgmiReqProduceItem = 1254,
    [pbr::OriginalName("EGMI_REQ_PICK_ITEM")] EgmiReqPickItem = 1255,
    [pbr::OriginalName("EGMI_REQ_ACCEPT_TASK")] EgmiReqAcceptTask = 1256,
    [pbr::OriginalName("EGMI_REQ_COMPELETE_TASK")] EgmiReqCompeleteTask = 1257,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ONLINE_NOTIFY")] EgmiAckOnlineNotify = 1290,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OFFLINE_NOTIFY")] EgmiAckOfflineNotify = 1291,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_CLAN")] EgmiReqCreateClan = 1300,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATE_CLAN")] EgmiAckCreateClan = 1301,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_CLAN")] EgmiReqJoinClan = 1302,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_JOIN_CLAN")] EgmiAckJoinClan = 1303,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_CLAN")] EgmiReqLeaveClan = 1304,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_CLAN")] EgmiAckLeaveClan = 1305,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPR_CLAN")] EgmiReqOprClan = 1306,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPR_CLAN")] EgmiAckOprClan = 1307,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SEARCH_CLAN")] EgmiReqSearchClan = 1308,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SEARCH_CLAN")] EgmiAckSearchClan = 1309,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPR_CLANINFO")] EgmiReqOprClaninfo = 1310,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPR_CLANINFO")] EgmiAckOprClaninfo = 1311,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CLANECTYPEINFO")] EgmiReqClanectypeinfo = 1312,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLANECTYPEINFO")] EgmiAckClanectypeinfo = 1313,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_SET_CLANECTYPEINFO")] EgmiSetClanectypeinfo = 1314,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ReqEnterGuildEctype")] EgmiReqEnterGuildEctype = 1315,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CREATE_CHATGROUP")] EgecReqCreateChatgroup = 1400,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_CREATE_CHATGROUP")] EgecAckCreateChatgroup = 1401,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_JOIN_CHATGROUP")] EgecReqJoinChatgroup = 1402,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_JOIN_CHATGROUP")] EgecAckJoinChatgroup = 1403,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_LEAVE_CHATGROUP")] EgecReqLeaveChatgroup = 1404,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_LEAVE_CHATGROUP")] EgecAckLeaveChatgroup = 1405,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SUBSCRIPTION_CHATGROUP")] EgecReqSubscriptionChatgroup = 1406,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CANCELSUBSCRIPTION_CHATGROUP")] EgecReqCancelsubscriptionChatgroup = 1407,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INVITE_CHATGROUP")] EgecReqInviteChatgroup = 1408,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INVITE_CHATGROUP")] EgecAckInviteChatgroup = 1409,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_KICK_CHATGROUP")] EgecReqKickChatgroup = 1410,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_KICK_CHATGROUP")] EgecAckKickChatgroup = 1411,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CHATGROUP_TO_TEAM")] EgecReqChatgroupToTeam = 1450,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_CHATGROUP_TO_TEAM")] EgecAckChatgroupToTeam = 1451,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INTENSIFYLEVEL_TO_EQUIP")] EgecReqIntensifylevelToEquip = 1500,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INTENSIFYLEVEL_TO_EQUIP")] EgecAckIntensifylevelToEquip = 1501,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_HOLE_TO_EQUIP")] EgecReqHoleToEquip = 1502,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_HOLE_TO_EQUIP")] EgecAckHoleToEquip = 1503,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INLAYSTONE_TO_EQUIP")] EgecReqInlaystoneToEquip = 1504,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INLAYSTONE_TO_EQUIP")] EgecAckInlaystoneToEquip = 1505,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_ELEMENTLEVEL_TO_EQUIP")] EgecReqElementlevelToEquip = 1506,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_ELEMENTLEVEL_TO_EQUIP")] EgecAckElementlevelToEquip = 1507,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_WEAR_EQUIP")] EgecWearEquip = 1508,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_TAKEOFF_EQUIP")] EgecTakeoffEquip = 1509,
    /// <summary>
    ///                                
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SET_FIGHT_HERO")] EgecReqSetFightHero = 1520,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SWITCH_FIGHT_HERO")] EgecReqSwitchFightHero = 1521,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_MINING_TITLE")] EgecReqMiningTitle = 1600,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_MINING_TITLE")] EgecAckMiningTitle = 1601,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SEND_MAIL")] EgecReqSendMail = 1700,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_DRAW_MAIL")] EgecReqDrawMail = 1701,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_DELETE_MAIL")] EgecReqDeleteMail = 1702,
    /// <summary>
    ///clone
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_ENTRY")] EgmiAckCloneObjectEntry = 1800,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_LEAVE")] EgmiAckCloneObjectLeave = 1801,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_PROPERTY_ENTRY")] EgmiAckCloneObjectPropertyEntry = 1802,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_RECORD_ENTRY")] EgmiAckCloneObjectRecordEntry = 1803,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_INT")] EgmiAckClonePropertyInt = 1810,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_FLOAT")] EgmiAckClonePropertyFloat = 1811,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_STRING")] EgmiAckClonePropertyString = 1812,
    /// <summary>
    ///EGMI_ACK_CLONE_PROPERTY_DOUBLE				= 1813;			//
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_OBJECT")] EgmiAckClonePropertyObject = 1814,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQSWICHSERVER")] EgmiReqswichserver = 1840,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACKSWICHSERVER")] EgmiAckswichserver = 1841,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_TEAM")] EgmiReqCreateTeam = 1860,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATE_TEAM")] EgmiAckCreateTeam = 1861,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_TEAM")] EgmiReqJoinTeam = 1862,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_JOIN_TEAM")] EgmiAckJoinTeam = 1863,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_TEAM")] EgmiReqLeaveTeam = 1864,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_TEAM")] EgmiAckLeaveTeam = 1865,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_INVITE_TEAM")] EgmiReqInviteTeam = 1866,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPRMEMBER_TEAM")] EgmiReqOprmemberTeam = 1867,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPRMEMBER_TEAM")] EgmiAckOprmemberTeam = 1868,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_TEAM_ENTER_ECTYPE")] EgmiReqTeamEnterEctype = 1869,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_TEAM_ENTER_ECTYPE")] EgmiAckTeamEnterEctype = 1870,
    /// <summary>
    //////////////////////MapModule/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_INFO")] EgmiReqMapGridInfo = 1900,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_INFO")] EgmiAckMapGridInfo = 1901,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BIG_MAP_INFO")] EgmiReqBigMapInfo = 1902,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_BIG_MAP_INFO")] EgmiAckBigMapInfo = 1903,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_HOLD_MAP_GRID")] EgmiReqHoldMapGrid = 1910,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_HOLD_MAP_GRID")] EgmiAckHoldMapGrid = 1911,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_MSG_MAP_GRID")] EgmiReqLeaveMsgMapGrid = 1912,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_MSG_MAP_GRID")] EgmiAckLeaveMsgMapGrid = 1913,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_GET_MAP_GRID_AWARD")] EgmiReqGetMapGridAward = 1914,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_GET_MAP_GRID_AWARD")] EgmiAckGetMapGridAward = 1915,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_HUNTING")] EgmiReqMapGridHunting = 1916,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_HUNTING")] EgmiAckMapGridHunting = 1917,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_KING_WAR")] EgmiReqMapGridKingWar = 1918,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_KING_WAR")] EgmiAckMapGridKingWar = 1919,
    /// <summary>
    //////////////////////GM MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_INT")] EgmiReqCmdPropertyInt = 10000,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_STR")] EgmiReqCmdPropertyStr = 10001,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_OBJECT")] EgmiReqCmdPropertyObject = 10002,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_FLOAT")] EgmiReqCmdPropertyFloat = 10003,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_INT")] EgmiReqCmdRecordInt = 10004,
    /// <summary>
    ///ַ
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_STR")] EgmiReqCmdRecordStr = 10005,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_OBJECT")] EgmiReqCmdRecordObject = 10006,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_FLOAT")] EgmiReqCmdRecordFloat = 10007,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_NORMAL")] EgmiReqCmdNormal = 10008,
    [pbr::OriginalName("EGMI_REQ_QUERY_SERVER_STATUS")] EgmiReqQueryServerStatus = 10200,
    /// <summary>
    //////////////////////Base SLG MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BUY_FORM_SHOP")] EgmiReqBuyFormShop = 20000,
    [pbr::OriginalName("EGMI_ACK_BUY_FORM_SHOP")] EgmiAckBuyFormShop = 20001,
    [pbr::OriginalName("EGMI_REQ_MOVE_BUILD_OBJECT")] EgmiReqMoveBuildObject = 20002,
    [pbr::OriginalName("EGMI_ACK_MOVE_BUILD_OBJECT")] EgmiAckMoveBuildObject = 20003,
    [pbr::OriginalName("EGMI_REQ_UP_BUILD_LVL")] EgmiReqUpBuildLvl = 20101,
    [pbr::OriginalName("EGMI_REQ_CREATE_ITEM")] EgmiReqCreateItem = 20102,
    [pbr::OriginalName("EGMI_REQ_BUILD_OPERATE")] EgmiReqBuildOperate = 20103,
    /// <summary>
    //////////////////////Base SHARE-TOOL MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SEARCH_TO_SHARE")] EgmiReqSearchToShare = 30000,
    [pbr::OriginalName("EGMI_ACK_SEARCH_TO_SHARE")] EgmiAckSearchToShare = 30001,
    [pbr::OriginalName("EGMI_REQ_SHARE_TO_ATART")] EgmiReqShareToAtart = 30002,
    [pbr::OriginalName("EGMI_ACK_SHARE_TO_ATART")] EgmiAckShareToAtart = 30003,
  }

  /// <summary>
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  ///PropertyType
  /// </summary>
  public enum ESkillType {
    /// <summary>
    ///this kind of skill just can damage one object
    /// </summary>
    [pbr::OriginalName("EST_BRIEF_SINGLE")] EstBriefSingle = 0,
    /// <summary>
    ///this kind of skill can damage multiple objects
    /// </summary>
    [pbr::OriginalName("EST_BRIEF_GROUP")] EstBriefGroup = 1,
    /// <summary>
    ///this kind of bullet just can damage one object
    /// </summary>
    [pbr::OriginalName("EST_BULLET_SINGLE")] EstBulletSingle = 2,
    /// <summary>
    ///this kind of bullet can damage multiple objects via rebound
    /// </summary>
    [pbr::OriginalName("EST_BULLET_REBOUND")] EstBulletRebound = 3,
    /// <summary>
    ///this kind of bullet can damage multiple objects who around the target when the bullet touched the target object
    /// </summary>
    [pbr::OriginalName("EST_BULLET_TARGET_BOMB")] EstBulletTargetBomb = 4,
    /// <summary>
    ///this kind of bullet can damage multiple objects  who around the target when the bullet arrived the position
    /// </summary>
    [pbr::OriginalName("EST_BULLET_POS_BOMB")] EstBulletPosBomb = 5,
  }

  public enum EItemType {
    /// <summary>
    ///the equipment which can add props
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EitEquip = 0,
    /// <summary>
    ///the gem ca be embed to the equipment
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EitGem = 1,
    /// <summary>
    ///expendable items for player, such as a medicine that cures
    /// </summary>
    [pbr::OriginalName("EIT_ITEM")] EitItem = 2,
    /// <summary>
    ///special items that can call a hero or others
    /// </summary>
    [pbr::OriginalName("EIT_CARD")] EitCard = 3,
    /// <summary>
    ///special items can do what you want to do
    /// </summary>
    [pbr::OriginalName("EIT_TOKEN")] EitToken = 4,
  }

  /// <summary>
  ///the sub items type of EIT_EQUIP
  /// </summary>
  public enum EGameEquipSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_WEAPON")] EquiptypeWeapon = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_HELMET")] EquiptypeHelmet = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_ARMOR")] EquiptypeArmor = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_WRIST")] EquiptypeWrist = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_PANT")] EquiptypePant = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_BOOT")] EquiptypeBoot = 5,
  }

  /// <summary>
  ///the sub items type of EIT_GEM
  /// </summary>
  public enum EGameGemSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_ATK")] EggstypeGemAtk = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_DEF")] EggstypeGemDef = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_FIRE")] EggstypeGemFire = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_LIGHT")] EggstypeGemLight = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_WIND")] EggstypeGemWind = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_ICE")] EggstypeGemIce = 6,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_POISON")] EggstypeGemPoison = 7,
  }

  /// <summary>
  ///the sub items type of EIT_ITEM
  /// </summary>
  public enum EGameItemSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_WATER")] EgitItemWater = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_DIAMOND")] EgitItemDiamond = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_CURRENCY")] EgitItemCurrency = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_EXP")] EgitItemExp = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_HP")] EgitItemHp = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_MP")] EgitItemMp = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_SP")] EgitItemSp = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_PACK")] EgitItemPack = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_MEMORY_POS")] EgitItemMemoryPos = 8,
  }

  /// <summary>
  ///the sub items type of EIT_CARD
  /// </summary>
  public enum EGameCardSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGCST_UNKNOW")] EgcstUnknow = 0,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("EGCST_STRENGTH")] EgcstStrength = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGCST_AGILITY")] EgcstAgility = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGCST_INTELLIGENCE")] EgcstIntelligence = 3,
  }

  /// <summary>
  ///the sub items type of EIT_TOKEN
  /// </summary>
  public enum EGameTokenSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_REBORN")] EgtstTokenReborn = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_POSITION")] EgtstTokenPosition = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_BOUNTY")] EgtstTokenBounty = 2,
    /// <summary>
    ///a token that can join a activity
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_ACTIVITY")] EgtstTokenActivity = 3,
    /// <summary>
    ///a token that can call a building or power
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_BUILD")] EgtstTokenBuild = 4,
  }

  /// <summary>
  /// </summary>
  public enum EGameItemExpiredType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIET_NONE")] EgietNone = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIET_USE_TIMES")] EgietUseTimes = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIET_REAL_TIME")] EgietRealTime = 2,
    [pbr::OriginalName("EGIET_END_INDEX")] EgietEndIndex = 3,
  }

  public enum EDrawDropItemState {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_NONE")] EDrawStateNone = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_GAIN")] EDrawStateGain = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_RECV")] EDrawStateRecv = 2,
  }

  /// <summary>
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  /// </summary>
  public enum EGuildPowerType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CLAN_POWER_TYPE_NORMAL")] ClanPowerTypeNormal = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CLAN_POWER_TYPE_VICE_PRESIDENT")] ClanPowerTypeVicePresident = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("CLAN_POWER_TYPE_PRESIDENT")] ClanPowerTypePresident = 2,
  }

  /// <summary>
  /// </summary>
  public enum ETaskState {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_IN_PROCESS")] TaskInProcess = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_DONE")] TaskDone = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_DRAW_AWARD")] TaskDrawAward = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_FINISH")] TaskFinish = 3,
  }

  /// <summary>
  /// </summary>
  public enum ETaskType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_LEVEL_UPDATE_SOME_LEVEL")] TaskLevelUpdateSomeLevel = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_PASS_ECTYPE")] TaskPassEctype = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_PASS_ECTYPE_COUNT")] TaskPassEctypeCount = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_PASS_SOME_TYPE_ECTYPE_COUNT")] TaskPassSomeTypeEctypeCount = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_UPDATE_SKILL_COUNT")] TaskUpdateSkillCount = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_CONSUME_MONEY")] TaskConsumeMoney = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_CONSUME_DIAMOND")] TaskConsumeDiamond = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_ARENA_COUNT")] TaskArenaCount = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_KILL_MONSTER_COUNT")] TaskKillMonsterCount = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_KILL_SOME_MONSTER_COUNT")] TaskKillSomeMonsterCount = 9,
  }

  /// <summary>
  /// </summary>
  public enum EPVPType {
    [pbr::OriginalName("PVP_HOME")] PvpHome = 0,
    [pbr::OriginalName("PVP_INDIVIDUAL")] PvpIndividual = 1,
    [pbr::OriginalName("PVP_DOTA")] PvpDota = 2,
    [pbr::OriginalName("PVP_SURVIVAL")] PvpSurvival = 3,
    [pbr::OriginalName("PVP_CLAN_WAR")] PvpClanWar = 4,
    [pbr::OriginalName("PVP_CLAN_DUNGEON")] PvpClanDungeon = 5,
  }

  public enum EShopType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_UNKNOW")] EstUnknow = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_BUILDING")] EstBuilding = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_GOLD")] EstGold = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_ITEM")] EstItem = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_EQUIP")] EstEquip = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_GEM")] EstGem = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_CARD")] EstCard = 7,
  }

  public enum ERankType {
    [pbr::OriginalName("ERT_UNKNOW")] ErtUnknow = 0,
    [pbr::OriginalName("ERT_PLAYER_LEVEL")] ErtPlayerLevel = 1,
    [pbr::OriginalName("ERT_FIGHT_VALUE")] ErtFightValue = 2,
    [pbr::OriginalName("ERT_PLAYER_MONEY")] ErtPlayerMoney = 3,
    [pbr::OriginalName("ERT_CLAN_LEVEL")] ErtClanLevel = 4,
    [pbr::OriginalName("ERT_CLAN_KINGSOURCE")] ErtClanKingsource = 5,
  }

  /// <summary>
  ///NPCTypenpc
  /// </summary>
  public enum ENPCType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_NORMAL")] Normal = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_HERO")] Hero = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_TURRET")] Turret = 2,
  }

  public enum EMeleeType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETYPE_MELEE")] EtypeMelee = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETYPE_MELEE_DASH")] EtypeMeleeDash = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETYPE_RANGER")] EtypeRanger = 2,
  }

  public enum EEffectObjType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETARGETTYPE_ENEMY")] EtargettypeEnemy = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETARGETTYPE_SELF")] EtargettypeSelf = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETARGETTYPE_FRIEND")] EtargettypeFriend = 2,
  }

  /// <summary>
  ///PropertyType
  /// </summary>
  public enum EPropertyType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_UNKNOW")] EptUnknow = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_STRENGTH")] EptStrength = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_AGILITY")] EptAgility = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_INTELLIGENCE")] EptIntelligence = 3,
  }

  /// <summary>
  /// </summary>
  public enum EGameElementType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_FIRE")] EelementtypeFire = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_LIGHT")] EelementtypeLight = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_WIND")] EelementtypeWind = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_ICE")] EelementtypeIce = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_POISON")] EelementtypePoison = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_DARK")] EelementtypeDark = 5,
  }

  #endregion

}

#endregion Designer generated code
